CC=tcc -m64
MODS=alloc_win.o parambind0.o parambind1_win64.o parambind2_win64.o
AR=tcc -ar


../parambind64.a: $(MODS)
	$(AR) ../parambind64.a $(MODS)

%.o:
	$(CC) -c $@

clean:
	rm -f *.o
	rm -f ../parambind.a
